module.exports = [
  {
    name: 'Wireless Headphones',
    description: 'Over-ear wireless headphones with active noise cancellation and 30-hour battery life.',
    price: 79.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/headphones/400/300',
    stock: 25,
  },
  {
    name: 'Smart Watch',
    description: 'Fitness tracking smart watch with heart-rate monitor and 7-day battery life.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/smartwatch/400/300',
    stock: 15,
  },
  {
    name: 'Mechanical Keyboard',
    description: 'RGB backlit mechanical keyboard with hot-swappable switches.',
    price: 59.99,
    category: 'Electronics',
    image: 'https://picsum.photos/seed/keyboard/400/300',
    stock: 30,
  },
  {
    name: 'Cotton T-Shirt',
    description: 'Soft, breathable 100% cotton crew neck t-shirt.',
    price: 14.99,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/tshirt/400/300',
    stock: 100,
  },
  {
    name: 'Denim Jacket',
    description: 'Classic fit denim jacket, perfect for layering in any season.',
    price: 49.99,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/jacket/400/300',
    stock: 40,
  },
  {
    name: 'Running Shoes',
    description: 'Lightweight running shoes with responsive cushioning.',
    price: 89.99,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/shoes/400/300',
    stock: 35,
  },
  {
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated water bottle that keeps drinks cold for 24 hours or hot for 12.',
    price: 24.99,
    category: 'Home & Kitchen',
    image: 'https://picsum.photos/seed/bottle/400/300',
    stock: 60,
  },
  {
    name: 'Non-Stick Frying Pan',
    description: '10-inch non-stick frying pan with heat-resistant handle.',
    price: 34.99,
    category: 'Home & Kitchen',
    image: 'https://picsum.photos/seed/pan/400/300',
    stock: 20,
  },
  {
    name: 'Ceramic Coffee Mug Set',
    description: 'Set of 4 ceramic coffee mugs, dishwasher and microwave safe.',
    price: 19.99,
    category: 'Home & Kitchen',
    image: 'https://picsum.photos/seed/mug/400/300',
    stock: 50,
  },
  {
    name: 'Yoga Mat',
    description: 'Extra-thick non-slip yoga mat with carrying strap.',
    price: 22.99,
    category: 'Sports & Outdoors',
    image: 'https://picsum.photos/seed/yogamat/400/300',
    stock: 45,
  },
  {
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells, 5-25 lbs per hand.',
    price: 149.99,
    category: 'Sports & Outdoors',
    image: 'https://picsum.photos/seed/dumbbell/400/300',
    stock: 10,
  },
  {
    name: 'Camping Tent (4-Person)',
    description: 'Waterproof 4-person camping tent, sets up in under 5 minutes.',
    price: 119.99,
    category: 'Sports & Outdoors',
    image: 'https://picsum.photos/seed/tent/400/300',
    stock: 12,
  },
];
